# Chezmoi data file for cosmikase
# This file contains template variables used across dotfiles

# Theme configuration
theme: nord
themes_dir: ~/.local/share/cosmikase/themes

# Font settings
font_family: JetBrainsMono Nerd Font
font_size: 9

# Terminal padding
padding: 14





